### ISSUE TITLE
Hi

### ISSUE THREAD

**Issue by ghost** [daar/z80-pascal#1]
Hi,

I'm Niunio from Sourceforge.  I'm trying to contact with you but e-mails are returned with an error.

I'm interested on following the project but I can work on weed-ends and free time only.

The plan I have is to restart the compiler using Mr. Wirth's approach.  Current code was written using a tutorial about compilers, but then I read a revised version of "Compiler Construction" by Niklaus Wirth himself [ISBN 0-201-40353-6] and find it simpler and much more complete than the tutorial I was following.

I don't know how we can team up, I have no experience on SourceForge teamed projects, and no experience at all on GitHub.  May be you can help me with that.  At the moment this I'll revise the Pascal BNF description and may be I can also design a module diagram for the new compiler.

Reragds,
Guillermo "Ñuño" Martínez

**Comment by niuniomartinez** [comment]
Hi. Me again.  I've changed my user name because I didn't like it.

**Comment by daar** [comment]
Hi Guillermo,

It would be great to team up with you and work together. As a start I have added you as collaborator to this repository. If you prefer to work with SVN then you can still checkout the repository from GitHub via SVN. You can of course also just keep on working via SourceForge and either add me as team member, or I will send you patches that you can apply. Do not worry about the workflow, I will help you where needed.
As for contact. My email adress is dhkblaszyk at zeelandnet dot nl, so you can email me directly if you like. Then I can close this issue here. We can also hookup some day via IRC to discuss the details and how we will proceed.

Hope to hear from you soon!

Regards, Darius
